// apps/cli/templates/auth-clerk/web/nuxt/app/components/UserMenu.vue
<script setup lang="ts">
import { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/vue'
</script>

<template>
  <div>
    <SignedOut>
      <SignInButton>
        <UButton variant="outline">
          Sign In
        </UButton>
      </SignInButton>
    </SignedOut>
    
    <SignedIn>
      <UserButton />
    </SignedIn>
  </div>
</template>

// apps/cli/templates/auth-clerk/web/react/base/src/components/user-menu.tsx
import { UserButton, SignedIn, SignedOut, SignInButton } from "@clerk/clerk-react";
import { Button } from "./ui/button";

export default function UserMenu() {
  return (
    <div>
      <SignedOut>
        <SignInButton>
          <Button variant="outline">Sign In</Button>
        </SignInButton>
      </SignedOut>
      <SignedIn>
        <UserButton 
          appearance={{
            elements: {
              avatarBox: "w-8 h-8"
            }
          }}
        />
      </SignedIn>
    </div>
  );
}
